package at.htlhl.chatnet.navigation

sealed class Screens(val route: String) {
    object ChatsViewScreen : Screens("ChatsViewScreen")
    object CameraViewScreen : Screens("CameraViewScreen")
    object CameraPhotoScreen : Screens("CameraPhotoScreen")
    object DropInScreen : Screens("DropInScreen")
    object ChatViewScreen : Screens("ChatViewScreen")
    object ChatMateScreen : Screens("ChatMateScreen")
    object RandChatStartScreen : Screens("RandChatStartScreen")
    object RandChatScreen : Screens("RandChatScreen")
    object ProfileScreen : Screens("ProfileScreen")
    object LoginScreen : Screens("LoginScreen")
    object RegisterScreen : Screens("RegisterScreen")
    object FindUserScreen : Screens("FindUserScreen")
    object ProfileInfoScreen : Screens("ProfileInfoScreen")
    object ImageViewScreen : Screens("ImageViewScreen")
    object ForgotPasswordScreen : Screens("ForgotPasswordScreen")
    object RegisterWithGoogleScreen : Screens("RegisterWithGoogleScreen")
    object ProfilePictureView : Screens("ProfilePictureScreen")
    object TagSelectScreen : Screens("TagSelectScreen")
    object PublicProfileScreen : Screens("PublicProfileScreen")
    object LoginFlow: Screens("LoginFlow")
    object MainFlow: Screens("MainFlow")
}